### ISSUE TITLE
 Filters: Selected year 2023, but I see electrification technology 2030 in the filter pane

### ISSUE THREAD

**Issue by Dimitrismentis** [global-electrification-platform/explorer#118]

**Comment by Dimitrismentis** [comment]
yes, this may be clear to us, but it will be confusing to users. Can't the filter change to 2023 when the year changes to 2023 and the user applies changes?

**Comment by vgeorge** [comment]
@Dimitrismentis I believe that is the current behavior of the platform, the filter by electrification technology applies to the selected timestep.
