### ISSUE TITLE
Review behavior of range sliders

### ISSUE THREAD

**Issue by danielfdsilva** [global-electrification-platform/explorer#128]
Range sliders are difficult to control (ex: population, area). A possible solution would be to use steps to more concrete numbers or allow direct edition.

**Comment by bpstewar** [comment]
This is not an enhancement - it needs to be fixed or the sliders need to be removed

**Comment by vgeorge** [comment]
Resolved, now it is possible to enter values manually. Please reopen if there is any issue.
