### ISSUE TITLE
Download model data

### ISSUE THREAD

**Issue by danielfdsilva** [global-electrification-platform/explorer#133]
WB feedback
> Is there any way to download the data/documentation of the API?

**Comment by bpstewar** [comment]
We are looking specifically for tools to download the geospatial data presented on the platform: we can access a pdf describing the map, but right now there is no way to download GIS data or the results

**Comment by vgeorge** [comment]
We propose to perform the following changes to address this issue:

- Rename "Export" button to "Download";
- Add a toggle to this button, with the following options:
  - **Current view as PDF**: the existing PDF report
  - **Full Scenario Data**: the csv file for the current scenario, available in S3 (eg. mw-1-0_0_0_0_0_0.csv.zip)
  - **Country Clusters**: the shapefile for cluster geometries of the current country

@bpstewar @alekordESA please let us know if we can move forward with this approach. If that is the case, permissions on /GEP folder in WB S3 bucket must be set to public, as the files are not available from outside now:

https://s3.amazonaws.com/wbg-geography01/GEP/models/mw-1/explorer/mw-1-0_0_0_0_0_0.csv.zip

**Comment by bpstewar** [comment]
I would prefer the second two options direct to a page on EnergyData.info, rather than provide direct access to the data - the files are too big for most users to access, so we need to provide a bunch of contextual information

**Comment by vgeorge** [comment]
@alekordESA @bpstewar The download button was implemented as discussed last meeting. The live website now shows a "dropup" listing the three download options (pdf/geo/raw) with the the last two disabled for future implementation. Please review and lets us know if it is ok.

**Comment by vgeorge** [comment]
For the official launch, the buttons should link to the model page at https://energydata.info. Changes needed:

- [ ] Include and document link to cluster and model data in model config
- [ ] Populate the buttons with these links

**Comment by vgeorge** [comment]
I've updated the comment above with the remaing tasks for this issue. Please let me know if you have any comments. 

cc @bpstewar @akorkovelos @EricSoroos

**Comment by vgeorge** [comment]
This was wrongly closed, we still need to populate the URL links at the model files. Will add them when energy.info pages are ready.

I believe that instead of offering the download of bulk model files, which are expensive, the model page at energy.info could offer several zipfiles, one for each scenario. An user would be able to download a scenario directly and, if there is need to download all off them, he/she could reach the consortium via e-mail and request. @bpstewar, do you think this strategy could work?

**Comment by bpstewar** [comment]
The model files are now available on energydata.info (although still private for right now). What do you need to link the download link to the energydata.info pages?

**Comment by EricSoroos** [comment]
Each of the countries has a dataset page with links to the 4 files that we're serving: 

![image](https://user-images.githubusercontent.com/36156267/70615395-9dbfcf00-1c0c-11ea-903b-5c8e4a730172.png)

It's probably best to link once to this page in the dropdown.

This is a list of the datasets that are currently on the platform. 

[gep-data-links.xlsx](https://github.com/global-electrification-platform/explorer/files/3949943/gep-data-links.xlsx)

**Comment by vgeorge** [comment]
Download links are set in model config files like this:

https://github.com/global-electrification-platform/data-service/blob/5925b296c9bac650684c756dbf9211d0081f9455/fixtures/mw-1/mw-1.yml#L11-L13

To make them available at the front-end, all model configs should be updated with the links and reingested. 

cc @EricSoroos

**Comment by bpstewar** [comment]
Thanks, Vitor, is that something you will do?

**Comment by vgeorge** [comment]
@bpstewar, @EricSoroos suggested and I created a [repository to host model configuration files](https://github.com/global-electrification-platform/models-configs). We thought that it would be good to put these files under version control to have a better log of changes. If you prefer the previous approach, please let us know.

Regarding the download links, my understanding is that Eric would add them to files once the download URLs exist and perform the reingest on the production database.

**Comment by EricSoroos** [comment]
@vgeorge There are 4 resources in the datasets, including the additional contextual resources that are important for the interpretation of the contents of the other items. 

There should be one link to the dataset in the application, rather than the two that are there.

**Comment by EricSoroos** [comment]
I've sent a PR for the single link
