### ISSUE TITLE
Review platform copy

### ISSUE THREAD

**Issue by danielfdsilva** [global-electrification-platform/explorer#137]
WB feedback
> All the scenario headlines and options within need documentation and explanation - probably as little pop-up windows
Model export pdf still includes Lorem Ipsum placeholder text

These features are implemented, it is just a matter of adding the final copy

**Comment by olafveerman** [comment]
As @danielfdsilva mentions, from a technical perspective, the popups are implemented. In the model configuration, a `description` can be specified for each lever: http://devseed.com/gep-docs/preparing-the-data/levers/.

We'll be working with @alekordESA to make sure it's clear how to add and edit those descriptions.

**Comment by vgeorge** [comment]
I believe the reffered issues were solved when preparing for Trieste workshop. Please reopen if there is still fixes to be done.
