### ISSUE TITLE
How to configure layers

### ISSUE THREAD

**Issue by olafveerman** [global-electrification-platform/explorer#138]
WB question:
> Toggling layers - where do these layers come from, how do we control them?

**Comment by olafveerman** [comment]
Map layer can be configured through the model config file (ex: https://github.com/developmentseed/gep-data-service/blob/master/fixtures/models/mw-1.yml#L111-L149). All the documentation for the model can be found at http://devseed.com/gep-docs/preparing-the-data/model-configuration/

**Comment by vgeorge** [comment]
I believe this was addressed, closing.
