### ISSUE TITLE
Mobile/low-bandwidth experience

### ISSUE THREAD

**Issue by olafveerman** [global-electrification-platform/explorer#139]
issue raised by WB.

**Comment by olafveerman** [comment]
The full site is responsive and works on mobile devices with the exception of the data exploration view. The interactions in this section are complex to perform on small screens and would lead to a frustrating user experience. Instead, the site shows a message that the explorer works on tablet and up.

As for the bandwidth, we tried to optimize the data as much as possible, but this is a data heavy application and it will need bandwidth to properly function.

**Comment by vgeorge** [comment]
I believe the above clarifies the issue. Please reopen if there is any further questions.
