### ISSUE TITLE
Compare maps in PDF

### ISSUE THREAD

**Issue by olafveerman** [global-electrification-platform/explorer#140]
Feature request by WB:

> In the PDF export:
> Comparison maps
>  - Two time steps
>  - Two scenarios

Originally raised in #135.

This was not originally scoped, and would require a high level of effort to implement. Marking this as a future enhancement.

**Comment by crogate** [comment]
We were also hoping to add the data inputs to the PDF so that it becomes sort of a brochure of the country. Would that be possible?
