### ISSUE TITLE
Home page icons

### ISSUE THREAD

**Issue by clairenicolas** [global-electrification-platform/explorer#148]
The home page icons are not self explanatory (the country and documentation ones). Wold it be possible to have the name of the section appear when the cursor is on it?

**Comment by vgeorge** [comment]
Hi @clairenicolas, I believe you are refering to the icons on the navigation bar on the side. They already have a text box that appears when the icon is hovered, but it is showing placeholder text. We will update it.

**Comment by vgeorge** [comment]
@clairenicolas We have added more meaningful labels to the navigation buttons. Can you please review?

**Comment by vgeorge** [comment]
I believe this issue was addressed, please reopen if there is the need of any further changes.
