### ISSUE TITLE
Visualization issues in Edge

### ISSUE THREAD

**Issue by clairenicolas** [global-electrification-platform/explorer#149]
When opening the GEP explorer in Edge there are some visualization issues

**Comment by vgeorge** [comment]
@clairenicolas can you please provide details about the issues or share screenshots?

**Comment by clairenicolas** [comment]
![image](https://user-images.githubusercontent.com/14335408/58575023-55603700-820f-11e9-82cf-68f33d05a104.png)

**Comment by clairenicolas** [comment]
- GEP in the upper left corner
 - the images next to the country names

**Comment by vgeorge** [comment]
Country flags should now appear. We are still working on the GEP logo in the upper left corner.

**Comment by vgeorge** [comment]
Styles were updated, please review @clairenicolas.

**Comment by vgeorge** [comment]
I believe this was addressed, please reopen if errors persist.
