### ISSUE TITLE
Loading time for large models

### ISSUE THREAD

**Issue by vgeorge** [global-electrification-platform/explorer#150]
Scenarios for Mozambique are taking about 40s to load. That is the time the data service takes to query the database, prepare the data and return it to the client. At the implementation stage there was only the Malawi model, four times smaller, which did not allowed us to anticipate this situation. We reviewed the query process and there are no immediate opportunities to reduce response on the first time on scenario access, but it is possible to **implement a cache for subsequent queries**. Thus, the scenarios that were accessed at least one time will have a faster loading.

This is the ticket for cache implementation on the data-service:

https://github.com/developmentseed/gep-data-service/issues/51

**Comment by olafveerman** [comment]
Discussed this today with @bpstewar and Chiara, who agreed with this assessment and proposed solution.

**Comment by vgeorge** [comment]
Implemented and deployed, please reopen in case of problems.
