### ISSUE TITLE
Pull VT from energydata.info

### ISSUE THREAD

**Issue by olafveerman** [global-electrification-platform/explorer#151]
@vgeorge If the vector tiles for the settlements would be stored on energydata.info, could we pull those into the explorer?

**Comment by vgeorge** [comment]
In this [this map](https://energydata.info/dataset/tunisia-electricity-transmission-network-2017/resource/106984f1-8f7a-4041-9617-d461de4d3d75) energydata.info fetches Vector Tiles from Amazon S3. It seems that CORS is enabled, so it is posible to use vector tiles from there.
