### ISSUE TITLE
Content for "About" page

### ISSUE THREAD

**Issue by vgeorge** [global-electrification-platform/explorer#153]
Text and logos are needed.

Link: http://gep-explorer.surge.sh/about

cc @alekordESA @bpstewar

**Comment by alekordESA** [comment]
Please find a first go in the link below:

https://docs.google.com/document/d/1bd-OoaQsEJ1QZZ1YW-um74So_wiXVyyPjcLHx0RVapk/edit?usp=sharing

@bpstewar @carderne please review.

**Comment by carderne** [comment]
Have made extensive suggestions.

**Comment by alekordESA** [comment]
@vgeorge I have updated the last sentence in the document (... please refer to ...); please include. Also, the 3 url links I have included in the text, are missing. I assume this is related to #152 and html parsing?

**Comment by vgeorge** [comment]
Updated, please review: http://gep-explorer.surge.sh/about

**Comment by vgeorge** [comment]
@akorkovelos do we need to insert any additional logos?

**Comment by vgeorge** [comment]
@akorkovelos I believe we don't have all logos from consortium members at the Drive folder. Can you please provide the remaining ones?

**Comment by akorkovelos** [comment]
Number of scenarios in second paragraph of the About page narrative should be changed from 144 to 216.

**Comment by akorkovelos** [comment]
@bpstewar @nicolinalindblad can you please place the WB logo in the folder linked earlier in this thread? Also, (@bpstewar) is there a list of the supporting partners (non consortium members) whose support has been confirmed by your side and thus can be included here ?

**Comment by nicolinalindblad** [comment]
@vgeorge the ESMAP and WBG logos are updated in the folder (linked above). Let us know if you want them in another format than png. 

@akorkovelos we are working on the list of supporters.

**Comment by nicolinalindblad** [comment]
We have added a [subfolder](https://drive.google.com/drive/folders/1NKzouSX7M1Goo2gSgMQchmveXoKMpago) for the organisations that have contributed and are endorsing the platform. Could these please be added under a third subcategory _'In collaboration with'_ . There are currently 3 logos there, but we are working on getting an additional 3 confirmed.

**Comment by vgeorge** [comment]
About page was updated. Please, review:

http://gep-explorer.surge.sh/about

cc @nicolinalindblad @akorkovelos

**Comment by nicolinalindblad** [comment]
Looks great @vgeorge only one thing, could you please remove the title "Credits" and only have 'Consortium' and 'In collaboration with. I just uploaded an additional logo ( Optimus) and will let you know if there are further updates. Thank you.

**Comment by nicolinalindblad** [comment]
@vgeorge would you be able to remove UNDP from the collaborators, they have not yet confirmed, so we will have to add them later if they do approve. There should not be any more pending for the launch. Thanks.

**Comment by nicolinalindblad** [comment]
@akorkovelos @babakkhavari @AndreasSahlberg for the KTH logo should the link be directed to the KTH-desa page or at least the English version of the official website (https://www.kth.se/en)

**Comment by AndreasSahlberg** [comment]
@nicolinalindblad the English version of the official website should be fine

**Comment by vgeorge** [comment]
Requested changes are now live at the production website.

**Comment by nicolinalindblad** [comment]
New update. Apology for the late updates, but would you please be able to upload [this](https://drive.google.com/file/d/1W7dvus863UYcmRTB7h5JuZLTZ-csbT1x/view?usp=sharing) (confirmed) version of the UNDP logo. Also, the SE4All logo has been updated to a [png.](https://drive.google.com/open?id=1FHSgAVCUicKOjyOgHbxTXTRTPm284fJ-). Also the link for the Facebook logo should be directed to: https://socialgood.fb.com/ I have asked them if they want a more specific link, but should do for now. Thank you!

**Comment by nicolinalindblad** [comment]
@vgeorge I just wanted to follow up on the UNDP logo - we will be presenting the GEP at the UNDP HQ tomorrow, so it is crucial to get it up. Apology for all the turns.

**Comment by nicolinalindblad** [comment]
Thank you that looks great - one last thing, that might have gotten lost in the thread, there are three missing consortium members: [ABB](https://drive.google.com/open?id=1MndglMWi_xtSNx2iE8xx9LDOmv5g_0FV), [University of Cambridge](https://drive.google.com/open?id=1k_bjLpOMV3Z24W8ido3BFOlwguSFjmUv), and [Google](https://drive.google.com/open?id=1VZY-Hn_q5BrJQOzmf98bKpR6nAx9Auux).

**Comment by vgeorge** [comment]
@nicolinalindblad I'm sorry, I missed that. Which URLs should they point to?

**Comment by nicolinalindblad** [comment]
They have not informed us about that - @bpstewar  should we just direct them to the main pages for now?

**Comment by vgeorge** [comment]
Also, please let me know if there is a specific order to display the logos.

**Comment by nicolinalindblad** [comment]
You can just put the generic websites for those for now. 
For the order: World Bank, ESMAP, KTH and then no specific order.

**Comment by olafveerman** [comment]
This page is live:

![image](https://user-images.githubusercontent.com/751330/65549387-700b9980-deeb-11e9-80d4-b4370be874dc.png)

Closing this issue.
