### ISSUE TITLE
Map keys for cluster geometries

### ISSUE THREAD

**Issue by vgeorge** [global-electrification-platform/explorer#157]
Each item of the following the table refers to a vector tileset of cluster geometries to be used on GEP Explorer. The layer id is composed by a two-letter ISO country code, followed by the layer version. This information can be included in model configuration files, as described in the [technical docs](https://global-electrification-platform.github.io/docs). 

Layer ID | Tileset URL
:---: | ---
ao-1|mapbox://globalelectrificationplatform.2klj89dp
bf-1|mapbox://globalelectrificationplatform.8k4rg29g
bi-1|mapbox://globalelectrificationplatform.8th7biyj
bj-1|mapbox://globalelectrificationplatform.a6hvu12j
bw-1|mapbox://globalelectrificationplatform.b412jfz8
cd-1|mapbox://globalelectrificationplatform.9srxunzd
cf-1|mapbox://globalelectrificationplatform.72nyo7w3
cg-1|mapbox://globalelectrificationplatform.73u7vxad
ci-1|mapbox://globalelectrificationplatform.adkcs0sq
cm-1|mapbox://globalelectrificationplatform.8zelt76g
dj-1|mapbox://globalelectrificationplatform.1ws3xejm
ga-1|mapbox://globalelectrificationplatform.49y1tlrc
gh-1|mapbox://globalelectrificationplatform.3ouo1afq
gm-1|mapbox://globalelectrificationplatform.8l5legy1
gn-1|mapbox://globalelectrificationplatform.e0biu3dm
gw-1|mapbox://globalelectrificationplatform.2ir1cht8
ke-1|mapbox://globalelectrificationplatform.5u024um9
km-1|mapbox://globalelectrificationplatform.9uj65nfg
lr-1|mapbox://globalelectrificationplatform.cvreyg5r
ls-1|mapbox://globalelectrificationplatform.5xtb1be6
mg-1|mapbox://globalelectrificationplatform.2t4qztj1
ml-1|mapbox://globalelectrificationplatform.3wzkfqr2
mr-1|mapbox://globalelectrificationplatform.0rwgasr6
mw-1|mapbox://globalelectrificationplatform.b3nu50ci
mz-1|mapbox://globalelectrificationplatform.b16974pm
na-1|mapbox://globalelectrificationplatform.5bf9sg9f
ne-1|mapbox://globalelectrificationplatform.431b9aa9
ng-1|mapbox://globalelectrificationplatform.1glx3k7n
rw-1|mapbox://globalelectrificationplatform.7gx5k0lv
sl-1|mapbox://globalelectrificationplatform.4mdb60f9
sn-1|mapbox://globalelectrificationplatform.0xeib28x
so-1|mapbox://globalelectrificationplatform.0elv2mxd
sz-1|mapbox://globalelectrificationplatform.83t8l1q7
td-1|mapbox://globalelectrificationplatform.c4jr5hy2
tg-1|mapbox://globalelectrificationplatform.cxm26q2o
tz-1|mapbox://globalelectrificationplatform.43l0pbb4
ug-1|mapbox://globalelectrificationplatform.crphi65b
za-1|mapbox://globalelectrificationplatform.6m34ne91
zm-1|mapbox://globalelectrificationplatform.cvdkqc80

This issue should remain open for reference.

**Comment by vgeorge** [comment]
We will have to use Devseed's Mapbox account for the launch as GEP's free-tier account is not working. I've reached Mapbox support, but I believe its safer to use Devseed paid account for the official launch.

@karitotp, could you please try to generate and upload the tileset for the smallest and biggest country first?

1. Download: 
  - er-1: s3://wbg-geography01/GEP/Clusters%20with%20WB%20admin/er-1.zip
  - et-1: s3://wbg-geography01/GEP/Clusters%20with%20WB%20admin/et-1.zip
2. Expand and convert to GeoJSON, using ogr2ogr or other appropriate tool
3. Generate the tileset with tippecanoe, like in the example below. Please following the naming convetion gep-{countryId}.mbtiles for the MBTiles:

```
tippecanoe -o gep-er-1.mbtiles er-1.geojson
```

4. Upload to Mapbox at https://studio.mapbox.com/tilesets

Please let me know if you have any questions.

**Comment by karitotp** [comment]
@vgeorge I uploaded 46 tileset to Devseed's Mapbox account.

Layer ID | Tileset ID
-- | --
ao-1 | devseed.9hzz88d7
bf-1 | devseed.a98iqqvf
bi-1 | devseed.1f5b1kcp
bj-1 | devseed.7p9es486
bw-1 | devseed.0gut3j5r
cd-1 | devseed.8ajha21o
cf-1 | devseed.35fqu74o
cg-1 | devseed.0h39bkk2
ci-1 | devseed.0l3977hy
cm-1 | devseed.6449fu03
dj-1 | devseed.al3v5bt1
er-1 | devseed.b3l99ngv
et-1 | devseed.5z0sj3ig
ga-1| devseed.76885yo0
gh-1| devseed.dlfa0r0o
gm-1| devseed.cel09x8z
gn-1| devseed.4ahgkqlq
gq-1| devseed.cddjj5y7
gw-1| devseed.4tcszxg9
ke-1| devseed.c5tdufx0
km-1| devseed.brqczg88
lr-1| devseed.0ypsxqtp
ls-1| devseed.cvmuqyoh
mg-1| devseed.7pch7veo
ml-1| devseed.c88s725w
mr-1| devseed.86vgam7h
mw-1| devseed.11yxwbes
mz-1| devseed.0nu9q22a
na-1| devseed.106csgf3
ne-1| devseed.7c48ry0g
ng-1| devseed.8jhwao44
rw-1| devseed.4tcszxg9
sd-1| devseed.0478qbzw
sl-1| devseed.0ibjiq80
sn-1| devseed.550s0kyt
so-1| devseed.5roi90t4
ss-1| devseed.0ml2hgby
st-1| devseed.6pg0xrwg
sz-1| devseed.dufxortc
td-1| devseed.57vxydwv
tg-1| devseed.bqdrek34
tz-1| devseed.2kg4oce4
ug-1| devseed.dkwxerqm
za-1| devseed.2mrtjp77
zm-1| devseed.0yxbrr6u
zw-1| devseed.b87uxolm
