### ISSUE TITLE
National clusters do not follow national boundaries

### ISSUE THREAD

**Issue by bpstewar** [global-electrification-platform/explorer#158]
I was perusing Malawi and I found a number of clusters that look like they fall outside the national boundary - this could be a problem. What are you using for the displayed national boundaries vs. the bounadries you used to create the clusters

![image](https://user-images.githubusercontent.com/5446296/58714011-cf202e00-8391-11e9-9b1e-5040362938da.png)

**Comment by babakkhavari** [comment]
The administrative boundaries used for the clustering process are from GADM. They are slightly larger than the ones provided by OSM which seems to have been used on the platform.

**Comment by bpstewar** [comment]
So what can we do about it? The final product cannot have clusters crossing borders for national level analysis? Can you change the basemap to something that follows GADM boundaries? Could you try using the WBG basemap instead?

https://api.mapbox.com/styles/v1/gsdpm/cioenuwii001maznontujohu8.html?title=true&access_token=pk.eyJ1IjoiZ3NkcG0iLCJhIjoiY2lqbmN5eG9mMDBndHVmbTU5Mmg1djF6MiJ9.QqFCD7tcmccysN8GUClW8w#1.1/-0.000000/0.000000/0

https://datacatalog.worldbank.org/dataset/world-bank-basemap-collection
(This second link might require special access to read)

**Comment by nicolinalindblad** [comment]
Pinging the importance of using the borders of the base layer mentioned by Ben above.

**Comment by babakkhavari** [comment]
Agree, I guess the first step would be to change the basemap used on the platform as this does not seem to correspond to the map sent by Ben neither, perhaps a change in basemap will solve the issue of clusters overlapping the borders. @vgeorge is it possible to change the basemap to the map that is linked by Ben?

**Comment by babakkhavari** [comment]
If a change in basemap does not fix the issue we will fix it our side

**Comment by vgeorge** [comment]
The borders from the base map come from [CIA World DataBank II](https://www.evl.uic.edu/pape/data/WDB). I've looked into [GADM](https://gadm.org/download_country_v3.html) and [Natural Earth](https://www.naturalearthdata.com/downloads/10m-cultural-vectors/10m-admin-0-countries), both seem less accurate than CIA's to me.

## Natural Earth
![Screenshot 2019-07-02 17 13 14](https://user-images.githubusercontent.com/329694/60528648-cbfbc300-9cec-11e9-9150-ab8a097b9a73.png)

## GADM
![Screenshot 2019-07-02 17 13 50](https://user-images.githubusercontent.com/329694/60528668-d6b65800-9cec-11e9-845a-ecbb7e237360.png)

It is possible to change the base map, but I believe those provided by Mapbox would display the same borders. I couldn't access look at the second link provided by @bpstewar. It must be publicly available to be used on the platform.

I believe this should be addressed via data side.

**Comment by babakkhavari** [comment]
@vgeorge and @bpstewar I have recieved the admin boundaries from the WB team. I will proceed to process the clusters with these borders so that they fit with the requirements from the WB-team.

**Comment by alekordESA** [comment]
@vgeorge, our analysis was modified so the clusters are in alignment with the WBG basemap @bpstewar mentioned in a previous comment. Can we change the basemaps on the explorer accordingly?

**Comment by vgeorge** [comment]
@akorkovelos, as we discussed today, clusters ids should match `featureId` field in scenario files. If they don't, scenarios files should be updated an reingested. I would suggest waiting for the migration conclusion so we don't have to ingest the update files two times.

**Comment by vgeorge** [comment]
@akorkovelos @babakkhavari, I can't add the WBG basemap to the explorer. In order to do so we need it publicly accessible and get its mapbox id. Is the `gsdpm` Mapbox account owned by the WB? Is it posible to reach them to make the map public and provide its mapbox id? Another way would be to migrate its style and raw data to the Mapbox GEP account, but we would still need to reach them so we don't have to build the map from scratch.

**Comment by akorkovelos** [comment]
@nicolinalindblad can you please response in the absence of @bpstewar?
Thanks.

**Comment by vgeorge** [comment]
@nicolinalindblad and @akorkovelos, you don't need to reach the authors anymore. with help from @danielfdsilva I was able to load the base map locally. It doesnt' show the clusters yet, I need to make some changes in order enable the them and will get back to you with the results.

**Comment by vgeorge** [comment]
I've managed to update the basemap with national borders provided by the WB-team, you can check at the live website:

- http://gep-explorer.surge.sh/explore/mw-1

The image below is from the same area reported by @bpstewar at the first comment:

![image](https://user-images.githubusercontent.com/329694/63518639-63a9b080-c4e9-11e9-905e-9dd02e3718b7.png)

@akorkovelos About the clusters files, in S3 exist two directories, `Clusters with GADM` and `Cluster with WB admin`, the second containing only Burundi. Should I update the clusters for all  countries using GADM dir files or wait for the remaining countries to be available in WB admin dir?

**Comment by akorkovelos** [comment]
@vgeorge please wait for the rest of the countries in WB admin dir. We have just received HRSL for the last 4 remaining countries for which WB clusters are prepared now. We expect to finish and upload them all on S3 soon; not later than CoB tomorrow.

**Comment by vgeorge** [comment]
I believe this issue was addressed, please reopen if it is not the case.
