### ISSUE TITLE
Overlay MV network actually used than T&D from energydata.info

### ISSUE THREAD

**Issue by akorkovelos** [global-electrification-platform/explorer#171]
At the moment the grid infrastructure that a user can overlay derives from [energydata.info](https://energydata.info/). This is not what was used in the electrification analysis; the latter used MV lines generated by [gridfinder](https://github.com/carderne/gridfinder). Those shall be prepared accordingly (@vgeorge could you please refer to documentation) and replace energydata.info data on the explorer.

**Comment by bpstewar** [comment]
@carderne Are you comfortable uploading the gridfinder results to EnergyData.info? I thought we discussed this and decided the data were not going to be uploaded.

**Comment by carderne** [comment]
Yes that will have to wait a few months until we publish the data I think.
