### ISSUE TITLE
Niger model (ne-1) config error

### ISSUE THREAD

**Issue by babakkhavari** [global-electrification-platform/explorer#172]
There seems to be an error in the interface for the Niger model. The subtitle says "Malawi OnSSET v1.0" 

![Niger](https://user-images.githubusercontent.com/35455877/59096220-9d234480-891a-11e9-8d67-bede39e9d544.PNG)

**Comment by vgeorge** [comment]
This is a model configuration file issue. I'll reingest after @alekordESA updates it.
