### ISSUE TITLE
Error when filter min/max are equal to zero

### ISSUE THREAD

**Issue by AndreasSahlberg** [global-electrification-platform/explorer#173]
Only one result seem to be loading fro Somalia

**Comment by vgeorge** [comment]
This is happening because property `CurrentMVLineDist` of Somalia is always equal to zero, probably an error in scenario output.

The Explorer shouldn't be breaking, though. I'll add a fix.

**Comment by vgeorge** [comment]
Fixed, please review: http://gep-explorer.surge.sh/explore/so-1

**Comment by AndreasSahlberg** [comment]
Results are loading as expected now, thanks!
