### ISSUE TITLE
Charting Error for Eswatinit

### ISSUE THREAD

**Issue by bpstewar** [global-electrification-platform/explorer#176]
http://gep-explorer.surge.sh/explore/sz-1?year=2030&scenario=0_0_1_0_0_0&filters=r4_85335%7Cr0_19%7C1_3_5_6_7%7Cr0_16%7Cr0_12%7Cr37_34734

I was exploring Eswatini, and this particular combination of levers appears to have broken the top chart

**Comment by olafveerman** [comment]
This is likely an issue with the underlying data. That being said, the chart in the Explorer should catch this error and handle it more gracefully.

**Comment by vgeorge** [comment]
The problem is that Redis has cached a deprecated API response. If you change the filters the chart is rendered properly. The resolution depends on https://github.com/global-electrification-platform/data-service/issues/61, because there is no easy way to flush Redis cache now.

**Comment by bpstewar** [comment]
Ok, makes sense, Victor, we can close this issue, with the understanding that flushing the Redis cache will be important

**Comment by vgeorge** [comment]
@bpstewar, I'll keep this open until we properly address the error.

**Comment by vgeorge** [comment]
Cached was renewed and the chart is showing properly now.
