### ISSUE TITLE
Migrate to new url?

### ISSUE THREAD

**Issue by bpstewar** [global-electrification-platform/explorer#180]
What is the process to migrate the platform to a new url? I see that the GEP link (http://www.globalelectrificationplatform.com/) directs to an old powerpoint from Yann Tavez. Can we have that point to the existing url, or migrate the application to that link?

**Comment by vgeorge** [comment]
@bpstewar The domain holder must to add CNAME records pointing to `gep-explorer.surge.sh` as described in section "Setting a CNAME" of this reference:

https://surge.sh/help/adding-a-custom-domain

Once it's done, we will update the explorer to use that domain.

**Comment by bpstewar** [comment]
I think this is now going to be handled by Derilinx as part of the migration to energydata.info, so no need to worry for now

**Comment by vgeorge** [comment]
@EricSoroos I've deployed successfully the countdown page, but it seems that there is some permission issue at http://gep-explorer-devseed-public.s3-website-us-west-2.amazonaws.com.

The command I did was: 

```
aws s3 sync --acl public-read ./dist s3://gep-explorer-devseed-public
```

**Comment by EricSoroos** [comment]
You shouldn't need to set the acl, everything on that bucket is public.

**Comment by vgeorge** [comment]
@EricSoroos Is it set as a website hosting bucket? I'm still getting forbidden access, even if I try to access a file directly:

https://gep-explorer-devseed-public.s3.amazonaws.com/index.html

**Comment by EricSoroos** [comment]
It is, and the public access portions are set up exactly the same as https://gep-explorer-public.s3.amazonaws.com/index.html.

I've made a change to it, I'm not sure it it will do the trick, but repush anyway, and if it doesn't work, I'll look at fixing it in cloudfront, which can have privs on the bucket.

**Comment by vgeorge** [comment]
Website is live at https://electrifynow.info.
