### ISSUE TITLE
Lever name error for Burundi

### ISSUE THREAD

**Issue by bpstewar** [global-electrification-platform/explorer#182]
The lever name for Electricity demant target is a bit turned around

http://gep-explorer.surge.sh/explore/bi-1

![image](https://user-images.githubusercontent.com/5446296/60296031-295dd180-98f3-11e9-89a8-b42a51e2936a.png)

**Comment by vgeorge** [comment]
This was a error at the model configuration file for Burundi. I've corrected it on S3 and updated production data.
