### ISSUE TITLE
Migrate GEP service to energydata.info

### ISSUE THREAD

**Issue by akorkovelos** [global-electrification-platform/explorer#183]
As per communication with Chiara and @bpstewar, it is time to migrate the GEP service to energydata.info. @olafveerman, @vgeorge can you please provide requirements from your side for doing so? @bpstewar can you please help make the right arrangements between DevSeed, energydata.info team and [derilinx](https://derilinx.com/)?

**Comment by vgeorge** [comment]
@alekordESA, I had a convertation with Derilinx yesterday to explain the platform architecture. Now they are getting familiar with the codebase so we can put together a migration plan. I'll get back to you once we have a better picture on how would this work.

**Comment by alekordESA** [comment]
Thanks @vgeorge. Is there any update on this so far?

**Comment by olafveerman** [comment]
@akorkovelos Derilinx is finalizing the migration plan and coordinating directly energydata.info.

**Comment by vgeorge** [comment]
We are coordinating with Derilinx and the migration is ongoing. Details can be followed via these milestones:

- https://github.com/global-electrification-platform/data-service/milestone/1
- https://github.com/global-electrification-platform/explorer/milestone/1

cc @EricSoroos
