### ISSUE TITLE
Add Global Solar Atlas as contextual layer

### ISSUE THREAD

**Issue by carderne** [global-electrification-platform/explorer#184]
@alekordESA 
Is this in the pipeline? What do you need from our side to make this happen?

**Comment by vgeorge** [comment]
Global Solar Atlas is available [here](https://globalsolaratlas.info/?c=27.605671,36.734402,3&m=sg:ghi).

This is an example tile query:

- https://tiles.globalsolaratlas.info/ghi/4/0_0/z4_7x8.jpg

It seems that the source tileset does not use [Web Mercator Projection](https://en.wikipedia.org/wiki/Web_Mercator_projection). We need to investigate which projection it is using and how to add it as a layer with MapboxGL.

This reference might be helpful: https://gist.github.com/tmcw/4954720#file-xyz_vs_tms-md
