### ISSUE TITLE
Add baseline to summary and tooltips

### ISSUE THREAD

**Issue by vgeorge** [global-electrification-platform/explorer#188]
As described by @bpstewar at https://github.com/global-electrification-platform/explorer/issues/144, it is necessary to include baseline information (population) to provide the full context for scenario analysis.

**Comment by vgeorge** [comment]
More specifics on this issue by @bpstewar:

> At the moment we are only providing the technology breakdown, but we are not showing the overall progress toward electrifying the population without access. We would like to show the number and percentage of the population already electrified and then the contribution of each technology, by 2025 and 2030. 

To address the above, I believe we would need to replace the first pie chart ("People connected") with something like this:

![image](https://user-images.githubusercontent.com/329694/63180806-edb7cc00-c046-11e9-9bfa-fd353b01f56c.png)


@bpstewar what do you think about this approach?

Regarding the input data, some questions for @akorkovelos:

- Is cluster population at base year represented by field `Pop`?
- Is connected population at base year represented by field `ElecPop`?
- How can we know the elec type at base year? 
- How can we calculate the amount of unconnected people, for baseline and timestep?

**Comment by akorkovelos** [comment]
@vgeorge responding to your questions:
* Population at base year is represented by ```Pop2018```
* Sum of people connected at based year by ```ElecPopCalib```
* Technology type at base year by ```FinalElecCode2018```. Note that in the base year we assume everything is grid connected thus above parameter equal to 1.
*  Number of unconnected people:
    * For the base year the easiest way is by ```Pop2018``` -```ElecPopCalib```
    * For the time step there are a couple of options giving the same results:
       - ```Pop2025``` -```PeopleConnected2025``` where the ```PeopleConnected2025 = Pop2025 x 
       ElecStatusIn2025``` as per #134 
       -  Sum ```Pop2025``` for rows that ```ElecStatusIn2025 == 0```
       -  Sum ```Pop2025``` for rows that ```FinalElecCode2025 == 99```

**Comment by vgeorge** [comment]
@akorkovelos @bpstewar please review the current implementation of the charts with real data:

## Malawi (mw-1)

<img width="203" alt="mw-1" src="https://user-images.githubusercontent.com/329694/64343917-501c4080-cfe5-11e9-8037-91179211dfb9.png">

## Gabon (ga-1)

<img width="202" alt="ga-1" src="https://user-images.githubusercontent.com/329694/64343987-7346f000-cfe5-11e9-98d4-b267bacd5988.png">

## Eswatini (es-1)

<img width="204" alt="es-1" src="https://user-images.githubusercontent.com/329694/64344003-7b069480-cfe5-11e9-835e-5d3352fe0cb8.png">

Are those samples in line with the expected model outputs?

**Comment by akorkovelos** [comment]
@vgeorge from a first look summaries seem correct for most scenarios but not the densification/intensification scenarios. For those two, summed population accounts only for grid connected population rather than the whole country. 

Look for example Rwanda, grid densification can reach about 8.92 million people which is about 56% of population in 2030. Yet the graph indicates 100% connected people. This call for:
a. Changing the legend to something ```Population Connected per Technology``` 
b. Review the way that summaries are calculated

Also, rounding up summaries make results look slightly odd on the graphs. I suggest allowing for 2 decimal precision when aggregating summaries, if possible.

**Comment by vgeorge** [comment]
@akorkovelos @babakkhavari here are fields used for calculating total and connected population (relevant code [here](https://github.com/global-electrification-platform/data-service/blob/a66be2b2c8f289cb3731a65c5eaa61254e47d133/cli/scenarios.js#L164-L173) and [here](https://github.com/global-electrification-platform/data-service/blob/a66be2b2c8f289cb3731a65c5eaa61254e47d133/cli/scenarios.js#L164-L173)):

- Timesteps: 
  - FinalElecCode{year}
  - NewCapacity{year}
  - Pop{year}
  - ElecStatusIn{year}
- Base year: 
  - FinalElecCode{year}
  - ElecPopCalib (for connected pop)
  - Pop{year}

We are reviewing the code that generate the summaries, if seems that the total pop is not correct in intermediate years. As discussed, it is helpful if you can provide scenarios with errors.

cc @danielfdsilva

**Comment by AndreasSahlberg** [comment]
Dear all,

To follow up on the discussion we had, please see an example of Burundi. If choosing the High demand target, and selecting 2025 we get the following results:

 

As we can see, there are a lot of PV mini-grids deployed between 2018-2025. This is also displayed in the summary chart on the right, where the summaries are correct for 2025. However, many of the mini-grids get connected to the grid between 2025-2030, which is shown when we switch the year:

  
![image](https://user-images.githubusercontent.com/35484968/65235892-c46fdd00-dad7-11e9-97ee-9ee8122223e6.png)


In this case, the summaries to the right are correct for 2030. However, the mini-grids that were there in 2025 are no longer seen in the summary chart. For this scenario he summary charts should display (regardless of which year is selected) deployment of mini-grids between 2018-2025, which is then phased out in favor of grid between 2025-2030.

![image](https://user-images.githubusercontent.com/35484968/65235919-cd60ae80-dad7-11e9-8675-cf80185b18ba.png)


It is worth pointing out that a settlement (cluster) can have different technology selections by 2025 and 2030, which is causing this.

**Comment by vgeorge** [comment]
We have deployed changes correcting the way of calculating summaries, could you please review?

cc @akorkovelos @AndreasSahlberg @babakkhavari 

I've moved the precision issue to #214, we didn't tested the impact of decimal places yet.
