### ISSUE TITLE
Country front page updates. 

### ISSUE THREAD

**Issue by nicolinalindblad** [global-electrification-platform/explorer#197]
Since there is currently only one model running the OnSSET could you please updated the following information: 

1. The info under the button directing back to the list of countries should be updated to 'Change country'.

2. The 'COUNTRY OnSSET V1.0' should be changed to 'GEP V1.0' 
![GEP_issues2](https://user-images.githubusercontent.com/45182007/64566741-a14d6c80-d324-11e9-80b7-2e7cae6cbd46.png)

**Comment by nicolinalindblad** [comment]
Thank you @olafveerman and @akorkovelos

**Comment by vgeorge** [comment]
Button label was updated. Also model name is hidden when there are no other models for the same country. If there is still the need to change model name we can resume discussing at #201.
