### ISSUE TITLE
Updates in model configuration files for official launch

### ISSUE THREAD

**Issue by vgeorge** [global-electrification-platform/explorer#201]
There are changes to be made at the model configuration files. This is an issue to coordinate that need to be made so Devseed can reingest them. @akorkovelos, can you please review the following and help me wrap up the changes needed?

- Rename model names from "Country ONSET V1.0" to "GEP 1.0", asked by @nicolinalindblad at #197
- Add globalsolaratlas.info data as a map layer, asked by @carderne at #184
- Update health site facilites for 7 countries, asked by @akorkovelos at #170
- Link to full scenario data #133
- Add MV lines, being discussed via email with @nicolinalindblad

**Comment by carderne** [comment]
@nicolinalindblad @akorkovelos Please loop me in on plans about adding MV lines, as this shouldn't be done until the data and methodology have gone through peer review.

**Comment by akorkovelos** [comment]
@vgeorge the main changes in the config files are the following:

* Final modification in semantics (e.g. #197, lever 2 name tags, description fixes) @nicolinalindblad @carderne @bpstewar glad if you could flag anything else to be modified before tomorrow's meeting.
* Toggle layers to be activated for a. Topographic map, b. Wind & Solar from energydata.info c. Healthsites (#170 #184)
* Link to full scenario data #133

We (KTH) can work on the first point and re-upload the yml files for all countries on S3. Then we will need your (DevSeed) support for the rest.

**Note!**
1. I suggest that we do not add any MV lines (as toggled layer) in this version (see @carderne comment above). We can keep the HV lines from energydata.info or disable them if you think this will cause confusion. **Let's discuss this tomorrow in the meeting**.
2. Other toggled layers (e.g. mobile phone coverage, travel time) will have to wait until we have access or can upload/share these data.
3. Full result files are ok to share. We have observed some discrepancies in the summary files we have uploaded on S3. We do not use these files anywhere at the moment but I am flagging this fyi. We are working on identifying the bug.

We are trying to keep record of loose ends [here](https://docs.google.com/document/d/1VSysJFZYSJCayw-Q74sAltQSJwzzzPbdm9FOKXZI5ug/edit?usp=sharing).

**Comment by nicolinalindblad** [comment]
The disputed area between Sudan and S. Sudan are both a dashed and a solid line- should only be dashed. 


![Capture](https://user-images.githubusercontent.com/45182007/64995942-9063a480-d8aa-11e9-81d3-5f35f4253378.JPG)

**Comment by vgeorge** [comment]
@nicolinalindblad the map problem was moved to a new issue as it isn't affected by model configuration.

**Comment by nicolinalindblad** [comment]
Thank you @vgeorge

**Comment by vgeorge** [comment]
@akorkovelos, as we discussed today, here is a sheet to coordinate better the model config layer updates. Your can add layer configurations for each country:

https://docs.google.com/spreadsheets/d/1N1sXjo2yGNoQdcUPFKq_xr716_FyolkVx-G1L_h-tP8/edit?usp=sharing

Once we have all the details set I'll transfer to the files and reingest.

**Comment by akorkovelos** [comment]
Naming on lever 2 has been updated. 
Working on #208.

**Comment by akorkovelos** [comment]
#208 is closed. Config files are now ready - from our (KTH) side - regarding updates on semantics and uploaded on S3.

**Comment by akorkovelos** [comment]
Following up on the toggle layers. @vgeorge please can you provide an update on the following:
* Healthsites - use shp that has been uploaded on S3 (#170)
* See whether we can use XYZ tiles hosted on AWS for [Solar GHI](https://globalsolaratlas.info/?c=4.127285,45.175781,3&m=sg:ghi) and [Wind Speed at 50m](https://globalwindatlas.info/)
* Topographic map
* Education facilities - Extracting OSM data and will upload findings on S3 (should be similar to healthsites) @babakkhavari 

In case layers are not available shall we keep them on the explorer as potential/upcoming options or discard them for the launch? @bpstewar @carderne?

**Comment by vgeorge** [comment]
@akorkovelos I've finish reingesting the lastest model configuration files from S3. Levers labels and descriptions should be updated now, you can review that part. Additional layers haven't been changed yet, I'm still working on them and will reingest when finished.

**Comment by akorkovelos** [comment]
A few changes on description of lever 5; yml files have been updated anew and uploaded on S3 under ```YML files Sep22```. Awaiting for a decision on additional layers from @vgeorge. Then config files will be placed in county folders as needed.

**Comment by vgeorge** [comment]
@akorkovelos, I've ingested the `YML files Sep22` of model configuration files. Regarding the maps:

- Healthsites (#170): included;
- Global Solar Atlas (#184) and Global Wind Atlas (#219): we need more info about the layer, as reported at the issues. I suggest removing them until we figure the problem;
- Topographic (#220): As reported at the issue, this would require a significative change at the Explorer to be addressed. I suggest removing. I've marked as an enhancement.
- Education facilities (#221): Opened a separated issue to track progress.

Please let me know if/when you update the files at S3.

**Comment by akorkovelos** [comment]
@vgeorge, many Healthsites (#170) seem to be missing on the explorer. See below shp Vs Explorer snapshot for  Nigeria. Actually I think it is just an overlaying issue. Can we bring healthsites at the top? Similar with wind and grid lines.?

![image](https://user-images.githubusercontent.com/18657007/65389002-2420ef00-dd49-11e9-8d68-c7d945e702c7.png)
![image](https://user-images.githubusercontent.com/18657007/65389010-3733bf00-dd49-11e9-83d7-fb9e9a4a7ed4.png)

I am removing Topographic (#220), Solar (#184) and Travel time options for now until we figure out a solution. I ll update the config files accordingly. I ll report back on education facilities (#221) asap.

**Comment by vgeorge** [comment]
I've added a comment on #170. You can leave Healthsites layers as is now. I think we can fix directly at Mapbox Studio and the map key won't change.

**Comment by akorkovelos** [comment]
New config files including final additional layers for the launch now uploaded on Se under ```YML files 22Sept_V2```. @vgeorge awaiting for re-ingest to provide a final review.

**Comment by vgeorge** [comment]
I'm sorry, @akorkovelos, I've added the the wrong map key in #221. It is changes now. Could you please update the files? You can use the same folder (_V2), if you prefer.

**Comment by vgeorge** [comment]
@akorkovelos I've updated the key locally and reingested the configs. All countries are updated now.

**Comment by akorkovelos** [comment]
@vgeorge Burundi uses still previous config file. Can you please update? Otherwise the rest seem ok!

**Comment by vgeorge** [comment]
There was an error in the file. I fixed, ingested and updated it at the S3 bucket in folder `YML files 22Sept_V2`.

**Comment by vgeorge** [comment]
@akorkovelos Alex, I've just noticed a map key error at the ao-1 file. I've fixed, reingested and updated S3. Could you please review the other countries?

**Comment by vgeorge** [comment]
I've made a review, all countries have the proper maps keys now.
