### ISSUE TITLE
Ivory Coast and Uganda data

### ISSUE THREAD

**Issue by vgeorge** [global-electrification-platform/explorer#207]
@babakkhavari I've reingested the tilesets for Ivory Coast and Uganda, I believe the problem is not there. Screenshots:

![image](https://user-images.githubusercontent.com/329694/65067422-64b1ee80-d97e-11e9-832d-915e2ea2ccdb.png)

![image](https://user-images.githubusercontent.com/329694/65068671-f589c980-d980-11e9-82ac-d2960f12464f.png)

Looking at scenarios files, some elec type values are not integers ("3.0"). Can you please review electrification types to ensure they are integers? We will need to reingest these countries.

**Comment by babakkhavari** [comment]
@vgeorge after you reingested the tiles the entire map appears for both countries. I will check some different scenarios and if they work I will mark it in your google doc as resolved.

**Comment by vgeorge** [comment]
Good! I recommend checking by sample if totals match from input tables, specially in the intermediate years. There might be features being dropped because of elec code type issue in input data.
