### ISSUE TITLE
Filter's do not allow manual edit of range slider

### ISSUE THREAD

**Issue by akorkovelos** [global-electrification-platform/explorer#209]

**Comment by vgeorge** [comment]
@akorkovelos this is available for testing. Now you can edit the value and, after leaving the input, the filter range will be updated. Please note that if the value is too low in comparison to the full range the slider won't change, but the filter will be set. You can see it working at https://github.com/global-electrification-platform/explorer/pull/216.

**Comment by akorkovelos** [comment]
@vgeorge filters seem to work fine now.
