### ISSUE TITLE
Change precision at population chart

### ISSUE THREAD

**Issue by vgeorge** [global-electrification-platform/explorer#214]
> Also, rounding up summaries make results look slightly odd on the graphs. I suggest allowing for 2 decimal precision when aggregating summaries, if possible.

_Originally posted by @akorkovelos in https://github.com/global-electrification-platform/explorer/issues/188#issuecomment-530003843_

**Comment by vgeorge** [comment]
@akorkovelos deployed, please review. A video of the expected behavior is available at https://github.com/global-electrification-platform/explorer/pull/215.

**Comment by olafveerman** [comment]
This was fixed. Closing.
