### ISSUE TITLE
Add Global Wind Atlas as contextual layer

### ISSUE THREAD

**Issue by vgeorge** [global-electrification-platform/explorer#219]
Browser the map [here](https://globalwindatlas.info/).

This is an example tile query:

- https://s3-eu-west-1.amazonaws.com/globalwindatlas2/pd_250_ad_100m_linear/9/278/286.png

It seems that the source tileset does not use [Web Mercator Projection](https://en.wikipedia.org/wiki/Web_Mercator_projection) or is a TMS service. We need to investigate and add it as a layer with MapboxGL.

See:
- https://github.com/global-electrification-platform/explorer/issues/218
- https://gist.github.com/tmcw/4954720#file-xyz_vs_tms-md

**Comment by nicolinalindblad** [comment]
@bpstewar you mentioned that it won't be possible to add the atlas at this time?
