### ISSUE TITLE
Can't access non-root URLs at production

### ISSUE THREAD

**Issue by vgeorge** [global-electrification-platform/explorer#224]
Site was successfully deployed to https://electrifynow.info, but it is not possible visit a link like this one:

https://electrifynow.info/countries

**Comment by vgeorge** [comment]
@EricSoroos can you have a look? I believe it is necessary to redirect all pages requests to index.html, like we do when serving directly from a S3 bucket.

**Comment by EricSoroos** [comment]
Ok, I've made the 403 error from S3 return /index.html at the cloudfront layer. 

This seems to be a different issue, index.html exists and is loaded but the front end is displaying an error: 

![image](https://user-images.githubusercontent.com/36156267/65422547-13cf4980-de07-11e9-81c0-fa0d45b9a8f8.png)

**Comment by vgeorge** [comment]
It seems to be working properly now, route /index.html is not supposed to exist.
