### ISSUE TITLE
Create GEP logo

### ISSUE THREAD

**Issue by nicolinalindblad** [global-electrification-platform/explorer#245]
Would it be possible to create a logo for the GEP, based on the graphics on the platform? Would be useful for marketing purposes.

**Comment by olafveerman** [comment]
@nicolinalindblad 
Here's a proposal for the GEP logo. It fits well within the current look and feel of the site, and can be easily used standalone.
Looking forward to your feedback. We're planning to generate the assets for this tomorrow, including version that can be easily used in a presentation.

![image (4)](https://user-images.githubusercontent.com/751330/68418566-789bf480-0166-11ea-98d8-771e282b9c4d.png)

Within the site:

![image](https://user-images.githubusercontent.com/751330/68418731-c9135200-0166-11ea-96b8-8ceb02016951.png)

**Comment by olafveerman** [comment]
Here are the new assets: [GEP_VisualAssets.zip](https://github.com/global-electrification-platform/explorer/files/3826165/GEP_VisualAssets.zip)

In this package, you'll find:

* a file with the vector version of the logo in 3 colours (colour/ darker/ white);
* the white version of the logo in png so you can use it on design decks for presentations (powerpoint etc).

cc @nicolinalindblad
