### ISSUE TITLE
Remove read the docs link

### ISSUE THREAD

**Issue by bpstewar** [global-electrification-platform/explorer#248]
The WB cannot support the read the docs because of the ads.

The issue of read the docs hosting will be raised on that repo, but for now, please remove the link from the main GEP page

**Comment by bpstewar** [comment]
https://github.com/global-electrification-platform/User_Guide/issues/2

**Comment by vgeorge** [comment]
@bpstewar link was removed. Contacts that were available in the docs were moved to the about page:

http://gep-explorer.surge.sh/about

**Comment by bpstewar** [comment]
I have removed the ads on the read the docs page, could the link be reinstated?

**Comment by vgeorge** [comment]
Fixed.
