### ISSUE TITLE
Remove ABB logo from about page

### ISSUE THREAD

**Issue by vgeorge** [global-electrification-platform/explorer#254]
@AndreasSahlberg @akorkovelos do you need to remove ABB contact as well?

https://electrifynow.energydata.info/about

**Comment by akorkovelos** [comment]
@vgeorge you can leave ABB contact details there as they are part of the consortium; so no harm there in my opinion. It is just the logo that we do not have clearance to use at the moment. I am sure the green light will come soon by them but until then ABB logo cannot be used.

**Comment by vgeorge** [comment]
@akorkovelos logo was removed. Please ping on this ticket when you have clearance to add it back.
