### ISSUE TITLE
Integrating new data from GSMA

### ISSUE THREAD

**Issue by bpstewar** [global-electrification-platform/explorer#269]
We have acquired web services for GSMA coverage from Harpers Collins. Could someone work with the technical experts from their side to integrate the maps into the GEP?

**Comment by jstuartmorton** [comment]
Hello. This is Stuart from Harper Collins.

**Comment by EricSoroos** [comment]
@bpstewar What layer(s) are you hoping to integrate?  I'm assuming that any of these will be additional layers in the 'extra layers' popup menu.

**Comment by bpstewar** [comment]
You are correct, Eric, we are looking to add layers to the additional layers popup.

Stuart, could you provide the layer information to Eric?

**Comment by jstuartmorton** [comment]
Hello Eric. I don't know if you have seen the talk about Mapbox layers. From what I have heard, you don't want Mapbox layers from our Mapbox account. Could you let me know how you would be expecting the data?
